name=Saver
version=1.1.0
author=AlexGyver <alex@alexgyver.ru>
maintainer=AlexGyver <alex@alexgyver.ru>
sentence=Lightweight library for storing and updating data in EEPROM and files
paragraph=CRC validation, automatic delayed saving, structure growth and safe file writes for Arduino and ESP
category=Data Storage
url=https://github.com/GyverLibs/Saver
architectures=*